### ISSUE TITLE
passing expression to r()

### ISSUE THREAD

**Issue by kforner** [r-pkgs/callr#10]
naive question: why not taking an expression argument to r() ? 

Is there any issue ? Because it also covers the function call case.
I mean 

> r(quote(summary(mycars)), vars = list(mycars)))

instead of 

> r(function(x) summary(x), args = list(mycars))

**Comment by gaborcsardi** [comment]
I think functions are cleaner. I also wanted to avoid doing NSE, although your `quote` way does that. Still, imo a function is simpler for people than a `quote`.

It is still not optimal, because we need to reset their environment manually, so you cannot pass a closure for example.

**Comment by gaborcsardi** [comment]
I don't mind handling expressions, do you want to submit a PR? I think we can just put the expressions into a function, and then everything just works.

**Comment by gaborcsardi** [comment]
I think it is cleaner to use functions, with the environment reset.

**Comment by kforner** [comment]
I don't understand why ? Could you give me an example ? 
My current work-around is:


#' execute some R code via the R executable 
#' 
#' @param code 	a language object. 
#' @param ... 	for callr::r 
#' 
#' @return the code evaluation  
#' @export 
run_r_code <- function(code, ...) {
   fun <- function() {}  
  body(fun) <- code   callr::r(fun, ...)
}

**Comment by gaborcsardi** [comment]
How do you pass an "argument" to `code`?

**Comment by kforner** [comment]
I can't. And I just understand now why you use functions. I had to use bquote my expressions to pass my local vars. Makes perfect sense.  

The point was to run simple commands such as run_r_code(quote(Sys.getwd())
It can be improved with : body(fun) <- substitute(code)
to be: `run_r_code(Sys.getwd()).`
I agree that this is only syntactic sugar, for me it felt more natural than giving a function.

**Comment by gaborcsardi** [comment]
I think it can be done with expressions, but it is just way simpler with a function, and function arguments. And it is not so much more to write `function() expr` than `expr`.

**Comment by kforner** [comment]
Definitely. As I said I missed the args passing problem. And anyway I can use my wrapper so everybody is happy ;)

Thanks again for callr. Did you know that you can tremendously speed up R CMD check using r_cmd() by setting repos to NULL ? It skips the utils::available.packages network download...

**Comment by gaborcsardi** [comment]
> Thanks again for callr. Did you know that you can tremendously speed up R CMD check using r_cmd() by setting repos to "" ? It skips the utils::available.packages network download...

That's a good idea. 

Btw. I want to "fix" the `available.packages` caching problem, so that it is kept across sessions and updates properly: https://github.com/r-hub/crancache/issues/14

**Comment by kforner** [comment]
> Btw. I want to "fix" the available.packages caching problem, so that it is kept across sessions and updates properly: r-hub/crancache#14

Very interesting indeed !
I was not aware of this r_hub project. Is it going well ? Who is driving it ?

**Comment by gaborcsardi** [comment]
Rhub in general? It is an R Consortium project.
