### ISSUE TITLE
rcmd without CMD

### ISSUE THREAD

**Issue by kforner** [r-pkgs/callr#11]
the rcmd() function, as the stated by the name, runs a 'R CMD xxx' command. 

What if I want to run 'R --version' ? Or R RHOME ? 
Should I'd be better off using r(function(x) R.version), but it's a bit slower. 

Thanks.

**Comment by gaborcsardi** [comment]
Good point. Actually the `R CMD` "functions" are so different, that I am not even sure that `rcmd()` is useful at all. E.g. some of them don't even start R, others do.

This said, it would probably make sense to have a function to call command line R.

**Comment by gaborcsardi** [comment]
I started working on this, but I think it is not really needed in practice, at least currently. THe three cases you could call this way are `R --help`, `R --version` and `R RHOME`.

`R --help` seems not very useful, the other two can be queried from within R, without starting another R process.

**Comment by kforner** [comment]
right. My use case was to switch from my own callr to yours, and I was using RHome. 
The other too can be queried from R, but it was a good way to be sure rcmd did use the proper R !
