### ISSUE TITLE
callr not working from testthat

### ISSUE THREAD

**Issue by hannesmuehleisen** [r-pkgs/callr#20]
We have a testthat test case that uses callr that does not work on travis or when called from R CMD check. Interestingly, it works fine if testthat is called directly. I made a demo repo at https://github.com/hannesmuehleisen/callrtestthattravistest. Error thrown: 
```
Running ‘testthat.R’
ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  cannot open the connection
  1: callr::r(do_something_dumb, show = TRUE) at testthat/test_01_callr.R:9
  2: r_internal(func, args, libpath = libpath, repos = repos, stdout = stdout, stderr = stderr, 
         error = error, cmdargs = cmdargs, show = show, callback = callback, system_profile = system_profile, 
         user_profile = user_profile, env = env)
  3: get_result(res)
  4: readRDS(res)
  5: gzfile(file, "rb")
```

Travis error is here: https://travis-ci.org/hannesmuehleisen/callrtestthattravistest/builds/189459759

**Comment by gaborcsardi** [comment]
I think you need to set `R_TESTS` to empty, otherwise R thinks it is running within `R CMD check` and does strange things. Btw. `r_safe` does that for you, maybe that should be the default....

**Comment by hannesmuehleisen** [comment]
cool thanks that fixed it!

**Comment by ajdamico** [comment]
thanks a lot!
