### ISSUE TITLE
I think recent changes have broken devel devtools on travis

### ISSUE THREAD

**Issue by jimhester** [r-pkgs/callr#22]
e.g. https://github.com/travis-ci/travis-ci/issues/7576

@gaborcsardi Looks to be an issue with how arguments are being escaped in callr or proccessx. This is the only recent change in devtools + dependencies that I think would cause it.

**Comment by gaborcsardi** [comment]
Oops. Sorry. Reverted and will investigate.

**Comment by gaborcsardi** [comment]
But then, how did an older devtools version fix this?

**Comment by jimhester** [comment]
Current devel devtools uses callr, older devtools does not!

**Comment by gaborcsardi** [comment]
I just just don't see it. The new version of `callr` will not require quoting external commands and arguments, but the only `devtools`-related code that uses `callr` with quoting is here: https://github.com/r-pkgs/pkgload/blob/master-clean-start/R/install-min.r#L15-L16
and it seems that this code was already removed from `pkgload`.

Am I missing sg?

**Comment by gaborcsardi** [comment]
Aha, I think I got it. Here:
https://github.com/r-pkgs/pkgbuild/blob/5ed87aa1c6f0482123d53a242df3dbc058e39f2c/R/compile-dll.r#L147-L148
and probably here as well:
https://github.com/r-pkgs/pkgbuild/blob/551a3c7e7f6f80dc8edc35039613c43f2a89e7fe/R/build.r#L71

Anyway, we need some (small) transitioning plan for these, because `callr` will not work with quoting. So at some point we just need to remove the quoting from `pkgbuild`, and I guess also add a remote to the newer `callr` version.

**Comment by jimhester** [comment]
Yeah I think pinning devtools / pkgbuild to callr before the quoting, then we can fix pkgbuild /devtools and update the remote.

**Comment by gaborcsardi** [comment]
@jimhester OK, here is the plan. Only `pkgbuild` is affected. `devtools` and `pkgapi` and `pkgdown` also use `callr`, but they are not affected.

- [ ] I submit a PR to `pkgbuild`, that pins `callr`
- [ ] @jimhester merges the PR
- [ ] I update `callr` to use `processx`.
- [ ] I submit a PR to `pkgbuild` that pins `callr` to the new version (?), and removes the `shQuote()`.
- [ ] @jimhester merges the PR
- [ ] ... time passes ...
- [ ] I put the new `callr` on CRAN (also needs `processx`, etc. on CRAN)
- [ ] I submit a PR to `pkgbuild` to remove the pinning and the callr remote entirely
- [ ] @jimhester merges the PR

OK?

**Comment by jimhester** [comment]
👍 , it is up to you if we pin the new callr version or just let it track the head of callr, in some ways I prefer the latter so we uncover issues sooner, but it is your call.

**Comment by gaborcsardi** [comment]
@jimhester pinning PR submitted.

**Comment by gaborcsardi** [comment]
> it is up to you if we pin the new callr version or just let it track the head of callr, in some ways I prefer the latter so we uncover issues sooner, but it is your call.

Can I pin to `HEAD` ? Just because if I just say `r-pkgs/callr`, then nothing indicates that the old version is bad....

**Comment by jimhester** [comment]
Both `r-pkgs/callr@HEAD` and `r-pkgs/callr@master` seem to work

**Comment by gaborcsardi** [comment]
Thanks, submitted another PR.

**Comment by gaborcsardi** [comment]
Thanks again. It seems that actually `devtools` needs a PR as well:
https://github.com/hadley/devtools/blob/2e3c4b692e3aecd7a4fd746e3000db1f4aa706bd/R/install.r#L158

**Comment by gaborcsardi** [comment]
@jimhester PR for devtools: https://github.com/hadley/devtools/pull/1493

**Comment by clocklear** [comment]
This appears to still be broken, in some capacity.  We're getting extra quotes in our devtools -> callr interactions:

```
> devtools::install_git('http://<our on-prem git solution>/dsc/coreFunctions.git', force = T)
Downloading git repo http://<our on-prem git solution>/dsc/coreFunctions.git
Installing coreFunctions
Running command /Library/Frameworks/R.framework/Resources/bin/R 
Arguments:
CMD
INSTALL
/private/var/folders/f5/7fhn61rj61nfq4s29ww0sk5jrmxt2m/T/RtmpklYkmZ/fileb1b368156e15
--library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 
Error: ERROR: cannot cd to directory ‘'/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests’
 
Installation failed: NULL : Command failed:
  
 Error: ERROR: cannot cd to directory ‘'/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests’
```

Note that `R CMD INSTALL` is trying to `cd` to the `‘'/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests’` directory, which is obviously a quoting problem.

**Comment by gaborcsardi** [comment]
Yes, I think the `shQuote` form here needs to be removed: 
https://github.com/hadley/devtools/blob/90a866b594389bacb2e579c358fd71736410606a/R/install.r#L145

@jimhester can you remove it pls?

**Comment by clocklear** [comment]
I made that change in our local copy and it's still trying to include the entire `opts` array in the `cd`.  It's hacky, but I had to also comment out the `--install-tests`.  I'm not sure why it's interpreting the entire `opts` as a path.

**Comment by jimhester** [comment]
Should be fixed by https://github.com/hadley/devtools/commit/ab176e699cef187feb5343a1b09c98b34a07db82

**Comment by gaborcsardi** [comment]
Oh yes, --install-tests should be separate argument....

**Comment by gaborcsardi** [comment]
@jimhester great, thanks!

**Comment by clocklear** [comment]
Agreed, thanks to both of you for the quick turn-around!
