### ISSUE TITLE
Spinner is messing up `devtools::check()` output

### ISSUE THREAD

**Issue by jimhester** [r-pkgs/callr#23]
E.g.

```
 OKhecking for file ‘devtools/DESCRIPTION’ ...
```

I can't figure out a good way to get back to the end of the previous line using ANSII escape codes to fix this, maybe you have some ideas.

**Comment by gaborcsardi** [comment]
There are ANSI sequences for this, but they are not very useful in this case, because `\r` is the only thing that works everywhere (Rgui, R.app, RStudio).

We'll figure out sg.  We can always disable the spinner.

**Comment by jimhester** [comment]
It would be fine if `\b` would backspace over newlines like it does in most languages, but it does not :-/

**Comment by gaborcsardi** [comment]
I think you can just turn the spinner off for now. Is that OK?

**Comment by jimhester** [comment]
I don't really mind the messed up output, but it would be nice to have a general solution to this problem and I am not sure one exists with how the escape codes are currently handled by the R console.

**Comment by gaborcsardi** [comment]
I can also turn off the spinner by default.

**Comment by gaborcsardi** [comment]
I think `devtools::check` could just call `callr` with `spinner = FALSE`. Here: https://github.com/hadley/devtools/blob/ab176e699cef187feb5343a1b09c98b34a07db82/R/check.r#L169
